#!/bin/bash

set -e

PairUp=/tmp/PairUp

source pairup-helper-functions

main() {
  set -x
  SECTION "Admin user setup:"

  SECTION "Make a pairup-env to preserve the state:"
  mkdir -p ~/.sh
  cat <<... > ~/.sh/pairup-env
export PAIRUP=true
export PAIRUP_ADMIN=%%admin_user%%
export PAIRUP_PAIR=%%pair_user%%
export PAIRUP_IPADDR=%%ip_address%%
export PAIRUP_STARTED="%%time_of_day%%"
export PAIRUP_REPO=%%pairup_repo%%
...

  SECTION "Copy known_hosts and config to .ssh/:"
  cp $PairUp/known_hosts .ssh/known_hosts
  cp $PairUp/ssh-config .ssh/config

  SECTION "Install ... dotfile management setup:"
  git clone git@github.com:sharpsaw/....git || continue?
  mv $PairUp/conf... .../conf
  .../... update || continue?
  .../... install || continue?

  SECTION "sudo pairup-install-software"
  (
    log="$PairUp/install.log"
    $section_command &>> $log || carp &>> $log &
  ) &

  SECTION "sudo pairup-install-cpan"
  (
    log="$PairUp/cpan.log"
    $section_command &>> $log || carp &>> $log &
  ) &

  SECTION "pairup-install-repos"
  (
    log="$PairUp/github.log"
    $section_command &>> $log || carp &>> $log &
  ) &

  SECTION "Start the PairUp custom tmux setup:"
  bash -l "$PairUp/bin/pairup" || true
}

[ "$0" == "${BASH_SOURCE[0]}" ] && main "$@";:
