#!/bin/bash

# This script will be run as root. It will:
# - add the admin user
# - add the pair user
# - install git
# - apt-get install requested pkgs in the background

set -e

export PairUp=/tmp/PairUp

PATH="$PairUp/bin:$PATH" \
  source helper-pairup-functions

main() {
  set -x

  SECTION "Root user setup:"

  SECTION "Create admin user: %%admin_user%%"
  {
    if [ "%%root_user%%" == root ]; then  # Don't addgroup for HPCloud
      addgroup admin || continue?
    fi
    adduser --disabled-password --gecos '' %%admin_user%% || continue?
    adduser %%admin_user%% admin || continue?

    mkdir -p /home/%%admin_user%%/.ssh
    chmod 700 /home/%%admin_user%%/.ssh
    cp $PairUp/user/%%admin_user%%/id_rsa.pub /home/%%admin_user%%/.ssh/authorized_keys
    chown -R %%admin_user%%:admin /home/%%admin_user%%/.ssh

    # No password for sudo:
    echo "%%admin_user%% ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
  }

  SECTION "Create pair user: %%pair_user%%"
  {
    adduser --disabled-password --gecos '' %%pair_user%% || continue?

    mkdir -p /home/%%pair_user%%/.ssh
    chmod 700 /home/%%pair_user%%/.ssh
    cp $PairUp/user/%%pair_user%%/id_rsa.pub /home/%%pair_user%%/.ssh/authorized_keys
    chown -R %%pair_user%%:%%pair_user%% /home/%%pair_user%%/.ssh
  }

  SECTION "Copy known hosts to .ssh/:"
  cp "$PairUp/known_hosts" .ssh/known_hosts

  SECTION "Preinstall the things we need to bootstrap:"
  apt-get update --yes
  apt-get install \
    build-essential \
    cpanminus \
    git-core \
    libssl-dev \
    weechat \
    --yes

  SECTION "Copy PairUp scripts into a PATH directory:"
  cp $PairUp/bin/* /usr/local/bin/

  SECTION "chown -R %%admin_user%%:admin '$PairUp'"
  chown -R %%admin_user%%:admin "$PairUp"

  SECTION "TODO - scramble root password"

  SECTION "DONE! root-setup is complete."
}

[ "$0" == "${BASH_SOURCE[0]}" ] && main "$@";:
