#!/bin/bash

pkgs=(
  ack-grep
  build-essential
  cpanminus
  exuberant-ctags
  git
  libjson-perl
  libjson-xs-perl
  tmux
  tree
  vim-nox
)
apt-get update --yes
apt-get install --yes "${pkgs[@]}"

cp $(dirname $0)/bin/pairup /usr/local/bin/
ln -s /usr/bin/ack-grep /usr/local/bin/ack

