#!/bin/bash

pkgs=(
  ack-grep
  apti autoreconf
  build-essential
  cpanminus
  exuberant-ctags
  libjson-perl
  libjson-xs-perl
  libtool
  pkg-config
  tmux
  tree
  vim-nox
)
apt-get install --yes "${pkgs[@]}"

# Symlink ack to ack-grep
ln -s /usr/bin/ack-grep /usr/local/bin/ack
