#!/usr/bin/env bash

set -e

[ -n "$PAIRUP_TEST_RUN" ] ||
  source ${PAIRUP_ROOT:=/usr/local/share/PairUp}/pairup-env
source $PAIRUP_ROOT/lib/pairup.bash

main() {
  local cmd= sudo= title= log= user=

  set -x

  TITLE "Admin user setup:"

  TITLE "Copy known_hosts and config to .ssh/:"
  cp $PAIRUP_ROOT/conf/known_hosts .ssh/known_hosts
  cp $PAIRUP_ROOT/conf/ssh-config .ssh/config

  TITLE "Install ... dotfile management setup:"
  git clone git@github.com:sharpsaw/....git || prompt_continue
  cp $PAIRUP_ROOT/conf/conf... .../conf
  .../... update || prompt_continue
  .../... install || prompt_continue

  title="Install common CPAN modules:" \
  sudo=true \
  log=true \
    RUN install-cpan-modules &

  title="Install common Debian packages:" \
  sudo=true \
  log=true \
    RUN install-debian-pkgs &

  title="Clone common GitHub repos:" \
  log=true \
    RUN clone-github-repos &

  title="Run custom install script:" \
  log='custom-install-script' \
    RUN "$PAIRUP_ROOT/conf/install" &

  TITLE "Start the PairUp custom tmux setup:"
  bash -l "$PAIRUP_ROOT/bin/pairup" || true
}

[ "$0" != "$BASH_SOURCE" ] || main "$@"
